### ISSUE TITLE
 Missing tags for versions 0.1.1, 0.1.2 and 1.0.0

### ISSUE THREAD

**Issue by paolobarbolini** [Actyx/sync_wrapper#14]
Releases 0.1.1, 0.1.2 and 1.0.0 haven't been tagged on GitHub. Could you please tag them?

You can find out the correct git commit id from:

* https://docs.rs/crate/sync_wrapper/0.1.1/source/.cargo_vcs_info.json
* https://docs.rs/crate/sync_wrapper/0.1.2/source/.cargo_vcs_info.json
* https://docs.rs/crate/sync_wrapper/1.0.0/source/.cargo_vcs_info.json

**Comment by rkuhn** [comment]
Thanks for the ping! I pushed the tags, so should  be fixed now.
